title: Vrinda Rakesh
description: Thoughts on books, math, and patterns in life
baseurl: ""
url: "https://vrindanmenon.github.io"

collections:
  booksorbed:
    output: true
    permalink: /booksorbed/:name/
  recursive-reflections:
    output: true
    permalink: /recursive-reflections/:name/
  learning-spaces:
    output: true
    permalink: /learning-spaces/:name/
  nature-diaries:
    output: true
    permalink: /nature-diaries/:name/
